//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDMall.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Action {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Action() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BDMall.Resources.Action", typeof(Action).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Activate 的本地化字符串。
        /// </summary>
        public static string Activate {
            get {
                return ResourceManager.GetString("Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Activate Account 的本地化字符串。
        /// </summary>
        public static string ActivateAccount {
            get {
                return ResourceManager.GetString("ActivateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Active 的本地化字符串。
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Combination Product 的本地化字符串。
        /// </summary>
        public static string AddCombination {
            get {
                return ResourceManager.GetString("AddCombination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add To Combosales Products 的本地化字符串。
        /// </summary>
        public static string AddCombosalesProduct {
            get {
                return ResourceManager.GetString("AddCombosalesProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add To Combosales Products (All combinations) 的本地化字符串。
        /// </summary>
        public static string AddCombosalesProductAllcombinations {
            get {
                return ResourceManager.GetString("AddCombosalesProductAllcombinations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Content 的本地化字符串。
        /// </summary>
        public static string AddContent {
            get {
                return ResourceManager.GetString("AddContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        public static string AddFolder {
            get {
                return ResourceManager.GetString("AddFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Main Category 的本地化字符串。
        /// </summary>
        public static string AddMainCategory {
            get {
                return ResourceManager.GetString("AddMainCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Menu 的本地化字符串。
        /// </summary>
        public static string AddMenu {
            get {
                return ResourceManager.GetString("AddMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Merchant Account 的本地化字符串。
        /// </summary>
        public static string AddMerchantAccount {
            get {
                return ResourceManager.GetString("AddMerchantAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add New 的本地化字符串。
        /// </summary>
        public static string AddNew {
            get {
                return ResourceManager.GetString("AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Payment Method 的本地化字符串。
        /// </summary>
        public static string AddPaymentMethod {
            get {
                return ResourceManager.GetString("AddPaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Promotion Banner 的本地化字符串。
        /// </summary>
        public static string AddPrmtBanner {
            get {
                return ResourceManager.GetString("AddPrmtBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Promotion Item 的本地化字符串。
        /// </summary>
        public static string AddPrmtItem {
            get {
                return ResourceManager.GetString("AddPrmtItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Promotion Merchant 的本地化字符串。
        /// </summary>
        public static string AddPrmtMerchant {
            get {
                return ResourceManager.GetString("AddPrmtMerchant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Promotion Product 的本地化字符串。
        /// </summary>
        public static string AddPrmtProduct {
            get {
                return ResourceManager.GetString("AddPrmtProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Product 的本地化字符串。
        /// </summary>
        public static string AddProduct {
            get {
                return ResourceManager.GetString("AddProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add To Related Products 的本地化字符串。
        /// </summary>
        public static string AddRelatedProduct {
            get {
                return ResourceManager.GetString("AddRelatedProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add To RelatedProducts (All combinations) 的本地化字符串。
        /// </summary>
        public static string AddRelatedProductAllCombinations {
            get {
                return ResourceManager.GetString("AddRelatedProductAllCombinations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Root Catalog 的本地化字符串。
        /// </summary>
        public static string AddRoot {
            get {
                return ResourceManager.GetString("AddRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Sub-Category 的本地化字符串。
        /// </summary>
        public static string AddSubCategory {
            get {
                return ResourceManager.GetString("AddSubCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add To NewsLetter List 的本地化字符串。
        /// </summary>
        public static string AddToNewsLetter {
            get {
                return ResourceManager.GetString("AddToNewsLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Apply Approve 的本地化字符串。
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Approve 的本地化字符串。
        /// </summary>
        public static string Approve {
            get {
                return ResourceManager.GetString("Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Assgin Roles 的本地化字符串。
        /// </summary>
        public static string AssginRoles {
            get {
                return ResourceManager.GetString("AssginRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Assigned 的本地化字符串。
        /// </summary>
        public static string Assigned {
            get {
                return ResourceManager.GetString("Assigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Back to List 的本地化字符串。
        /// </summary>
        public static string BacktoList {
            get {
                return ResourceManager.GetString("BacktoList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Batch Approve 的本地化字符串。
        /// </summary>
        public static string BatchApprove {
            get {
                return ResourceManager.GetString("BatchApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel Order 的本地化字符串。
        /// </summary>
        public static string CancelOrder {
            get {
                return ResourceManager.GetString("CancelOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change Image 的本地化字符串。
        /// </summary>
        public static string ChangeImage {
            get {
                return ResourceManager.GetString("ChangeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change Product 的本地化字符串。
        /// </summary>
        public static string ChangeProduct {
            get {
                return ResourceManager.GetString("ChangeProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close Current Tab 的本地化字符串。
        /// </summary>
        public static string CloseTab {
            get {
                return ResourceManager.GetString("CloseTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Complete Order 的本地化字符串。
        /// </summary>
        public static string CompleteOrder {
            get {
                return ResourceManager.GetString("CompleteOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm 的本地化字符串。
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy 的本地化字符串。
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy Product To Banner 的本地化字符串。
        /// </summary>
        public static string CopyPrmtProd {
            get {
                return ResourceManager.GetString("CopyPrmtProd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CopyToOtherLanguage 的本地化字符串。
        /// </summary>
        public static string CopyToOtherLanguage {
            get {
                return ResourceManager.GetString("CopyToOtherLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create Account 的本地化字符串。
        /// </summary>
        public static string CreateAccount {
            get {
                return ResourceManager.GetString("CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Version 的本地化字符串。
        /// </summary>
        public static string CreateNewVer {
            get {
                return ResourceManager.GetString("CreateNewVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Customization 的本地化字符串。
        /// </summary>
        public static string Customization {
            get {
                return ResourceManager.GetString("Customization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deactivate 的本地化字符串。
        /// </summary>
        public static string Deactivate {
            get {
                return ResourceManager.GetString("Deactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Def.Img.Pos. 的本地化字符串。
        /// </summary>
        public static string DefineImagePosition {
            get {
                return ResourceManager.GetString("DefineImagePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete From Combosales Products 的本地化字符串。
        /// </summary>
        public static string DeleteAccessoriesProduct {
            get {
                return ResourceManager.GetString("DeleteAccessoriesProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete Account 的本地化字符串。
        /// </summary>
        public static string DeleteAccount {
            get {
                return ResourceManager.GetString("DeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete All From Combosales Products 的本地化字符串。
        /// </summary>
        public static string DeleteALLAccessoriesProduct {
            get {
                return ResourceManager.GetString("DeleteALLAccessoriesProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete All Combinations From Combosales Products 的本地化字符串。
        /// </summary>
        public static string DeleteALLCombinationAccessoriesProduct {
            get {
                return ResourceManager.GetString("DeleteALLCombinationAccessoriesProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete All Combinations From Related Products 的本地化字符串。
        /// </summary>
        public static string DeleteALLCombinationRelatedProduct {
            get {
                return ResourceManager.GetString("DeleteALLCombinationRelatedProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete All From Related Products 的本地化字符串。
        /// </summary>
        public static string DeleteALLRelatedProducts {
            get {
                return ResourceManager.GetString("DeleteALLRelatedProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete Category 的本地化字符串。
        /// </summary>
        public static string DeleteCategory {
            get {
                return ResourceManager.GetString("DeleteCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete File 的本地化字符串。
        /// </summary>
        public static string DeleteFile {
            get {
                return ResourceManager.GetString("DeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string DeleteFolder {
            get {
                return ResourceManager.GetString("DeleteFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete Related Products 的本地化字符串。
        /// </summary>
        public static string DeleteRelatedProducts {
            get {
                return ResourceManager.GetString("DeleteRelatedProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Design 的本地化字符串。
        /// </summary>
        public static string Design {
            get {
                return ResourceManager.GetString("Design", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detail 的本地化字符串。
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Details&amp;Modify 的本地化字符串。
        /// </summary>
        public static string DetailsAndModify {
            get {
                return ResourceManager.GetString("DetailsAndModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disable Account 的本地化字符串。
        /// </summary>
        public static string DisableAccount {
            get {
                return ResourceManager.GetString("DisableAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DownLoad 的本地化字符串。
        /// </summary>
        public static string DownLoad {
            get {
                return ResourceManager.GetString("DownLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download ECShipLabel 的本地化字符串。
        /// </summary>
        public static string DownloadECShipLabel {
            get {
                return ResourceManager.GetString("DownloadECShipLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download Shiplabel 的本地化字符串。
        /// </summary>
        public static string DownloadhipLabel {
            get {
                return ResourceManager.GetString("DownloadhipLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DownLoad Template 的本地化字符串。
        /// </summary>
        public static string DownLoadTemplate {
            get {
                return ResourceManager.GetString("DownLoadTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create Shipping Label 的本地化字符串。
        /// </summary>
        public static string ECShipOrder {
            get {
                return ResourceManager.GetString("ECShipOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Category 的本地化字符串。
        /// </summary>
        public static string EditCategory {
            get {
                return ResourceManager.GetString("EditCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit customized settings 的本地化字符串。
        /// </summary>
        public static string EditCustSetting {
            get {
                return ResourceManager.GetString("EditCustSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Account 的本地化字符串。
        /// </summary>
        public static string EnableAccount {
            get {
                return ResourceManager.GetString("EnableAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export 的本地化字符串。
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extra Condition 的本地化字符串。
        /// </summary>
        public static string ExtraCondition {
            get {
                return ResourceManager.GetString("ExtraCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gen Code 的本地化字符串。
        /// </summary>
        public static string GenCode {
            get {
                return ResourceManager.GetString("GenCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generate Rules 的本地化字符串。
        /// </summary>
        public static string GenerateRules {
            get {
                return ResourceManager.GetString("GenerateRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generate express No 的本地化字符串。
        /// </summary>
        public static string GenExpNo {
            get {
                return ResourceManager.GetString("GenExpNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hidden 的本地化字符串。
        /// </summary>
        public static string Hidden {
            get {
                return ResourceManager.GetString("Hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图标 的本地化字符串。
        /// </summary>
        public static string IconList {
            get {
                return ResourceManager.GetString("IconList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import 的本地化字符串。
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert 的本地化字符串。
        /// </summary>
        public static string Insert {
            get {
                return ResourceManager.GetString("Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Kick out 的本地化字符串。
        /// </summary>
        public static string Kickout {
            get {
                return ResourceManager.GetString("Kickout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Linkup Existing “ShopThruPost” Account 的本地化字符串。
        /// </summary>
        public static string LinkupStp {
            get {
                return ResourceManager.GetString("LinkupStp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login 的本地化字符串。
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MailTracking 的本地化字符串。
        /// </summary>
        public static string MailTracking {
            get {
                return ResourceManager.GetString("MailTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Map Items 的本地化字符串。
        /// </summary>
        public static string MapItem {
            get {
                return ResourceManager.GetString("MapItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mark As Read 的本地化字符串。
        /// </summary>
        public static string MarkAsRead {
            get {
                return ResourceManager.GetString("MarkAsRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Member Search 的本地化字符串。
        /// </summary>
        public static string MemberSearch {
            get {
                return ResourceManager.GetString("MemberSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Merchant Handle 的本地化字符串。
        /// </summary>
        public static string MerchantHandle {
            get {
                return ResourceManager.GetString("MerchantHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modify 的本地化字符串。
        /// </summary>
        public static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modify Content 的本地化字符串。
        /// </summary>
        public static string ModifyContent {
            get {
                return ResourceManager.GetString("ModifyContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modify Merchant Account 的本地化字符串。
        /// </summary>
        public static string ModifyMerchantAccount {
            get {
                return ResourceManager.GetString("ModifyMerchantAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modify Payment Method 的本地化字符串。
        /// </summary>
        public static string ModifyPaymentMethod {
            get {
                return ResourceManager.GetString("ModifyPaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move 的本地化字符串。
        /// </summary>
        public static string Move {
            get {
                return ResourceManager.GetString("Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New 的本地化字符串。
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Next 的本地化字符串。
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pass 的本地化字符串。
        /// </summary>
        public static string Pass {
            get {
                return ResourceManager.GetString("Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Physical Delete 的本地化字符串。
        /// </summary>
        public static string PhysicalDelete {
            get {
                return ResourceManager.GetString("PhysicalDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Proceed 的本地化字符串。
        /// </summary>
        public static string Proceed {
            get {
                return ResourceManager.GetString("Proceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Process Data 的本地化字符串。
        /// </summary>
        public static string ProcessData {
            get {
                return ResourceManager.GetString("ProcessData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Publish 的本地化字符串。
        /// </summary>
        public static string Publish {
            get {
                return ResourceManager.GetString("Publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pull Off Shelves 的本地化字符串。
        /// </summary>
        public static string PullOff {
            get {
                return ResourceManager.GetString("PullOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Put On Shelves 的本地化字符串。
        /// </summary>
        public static string PutOn {
            get {
                return ResourceManager.GetString("PutOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh 的本地化字符串。
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upgrade Now 的本地化字符串。
        /// </summary>
        public static string RegHKPID2 {
            get {
                return ResourceManager.GetString("RegHKPID2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Decide Later 的本地化字符串。
        /// </summary>
        public static string RegLater {
            get {
                return ResourceManager.GetString("RegLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get Started “ShopThruPost” 的本地化字符串。
        /// </summary>
        public static string RegStp {
            get {
                return ResourceManager.GetString("RegStp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reject 的本地化字符串。
        /// </summary>
        public static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login again 的本地化字符串。
        /// </summary>
        public static string Relogin {
            get {
                return ResourceManager.GetString("Relogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove customized settings 的本地化字符串。
        /// </summary>
        public static string RemoveCustSetting {
            get {
                return ResourceManager.GetString("RemoveCustSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove Image 的本地化字符串。
        /// </summary>
        public static string RemoveImage {
            get {
                return ResourceManager.GetString("RemoveImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rename 的本地化字符串。
        /// </summary>
        public static string RenameFolder {
            get {
                return ResourceManager.GetString("RenameFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Replace 的本地化字符串。
        /// </summary>
        public static string Replace {
            get {
                return ResourceManager.GetString("Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Replaceable 的本地化字符串。
        /// </summary>
        public static string Replaceable {
            get {
                return ResourceManager.GetString("Replaceable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reply 的本地化字符串。
        /// </summary>
        public static string Reply {
            get {
                return ResourceManager.GetString("Reply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ReSend 的本地化字符串。
        /// </summary>
        public static string ReSend {
            get {
                return ResourceManager.GetString("ReSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resend Account Email 的本地化字符串。
        /// </summary>
        public static string ResendActForMerch {
            get {
                return ResourceManager.GetString("ResendActForMerch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ReSendMail 的本地化字符串。
        /// </summary>
        public static string ReSendMail {
            get {
                return ResourceManager.GetString("ReSendMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset 的本地化字符串。
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset Pwd. 的本地化字符串。
        /// </summary>
        public static string resetPWD {
            get {
                return ResourceManager.GetString("resetPWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restore 的本地化字符串。
        /// </summary>
        public static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ReTry 的本地化字符串。
        /// </summary>
        public static string ReTry {
            get {
                return ResourceManager.GetString("ReTry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ReUpload 的本地化字符串。
        /// </summary>
        public static string ReUpload {
            get {
                return ResourceManager.GetString("ReUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save And Apply 的本地化字符串。
        /// </summary>
        public static string SaveAndApply {
            get {
                return ResourceManager.GetString("SaveAndApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save&amp;SendMail 的本地化字符串。
        /// </summary>
        public static string SaveAndSend {
            get {
                return ResourceManager.GetString("SaveAndSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Design 的本地化字符串。
        /// </summary>
        public static string SaveDesign {
            get {
                return ResourceManager.GetString("SaveDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search 的本地化字符串。
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 select 的本地化字符串。
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select ALL 的本地化字符串。
        /// </summary>
        public static string SelectALL {
            get {
                return ResourceManager.GetString("SelectALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Selected 的本地化字符串。
        /// </summary>
        public static string Selected {
            get {
                return ResourceManager.GetString("Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select File 的本地化字符串。
        /// </summary>
        public static string SelectFile {
            get {
                return ResourceManager.GetString("SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send 的本地化字符串。
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Express redirection 的本地化字符串。
        /// </summary>
        public static string SendBack {
            get {
                return ResourceManager.GetString("SendBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send Image 的本地化字符串。
        /// </summary>
        public static string SendImg {
            get {
                return ResourceManager.GetString("SendImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send Mail 的本地化字符串。
        /// </summary>
        public static string SendMail {
            get {
                return ResourceManager.GetString("SendMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send Whatapps 的本地化字符串。
        /// </summary>
        public static string SendWhatapps {
            get {
                return ResourceManager.GetString("SendWhatapps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SetDefault 的本地化字符串。
        /// </summary>
        public static string SetDefault {
            get {
                return ResourceManager.GetString("SetDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show 的本地化字符串。
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ShowECShipLabel 的本地化字符串。
        /// </summary>
        public static string ShowECShipLabel {
            get {
                return ResourceManager.GetString("ShowECShipLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ShowShipLabel 的本地化字符串。
        /// </summary>
        public static string ShowShipLabel {
            get {
                return ResourceManager.GetString("ShowShipLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sorted 的本地化字符串。
        /// </summary>
        public static string Sorted {
            get {
                return ResourceManager.GetString("Sorted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start 的本地化字符串。
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop 的本地化字符串。
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 List 的本地化字符串。
        /// </summary>
        public static string TableList {
            get {
                return ResourceManager.GetString("TableList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Template Guideline 的本地化字符串。
        /// </summary>
        public static string TemplateGuidLine {
            get {
                return ResourceManager.GetString("TemplateGuidLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Turndown 的本地化字符串。
        /// </summary>
        public static string Turndown {
            get {
                return ResourceManager.GetString("Turndown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update 的本地化字符串。
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update Account 的本地化字符串。
        /// </summary>
        public static string UpdateAccount {
            get {
                return ResourceManager.GetString("UpdateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update Message 的本地化字符串。
        /// </summary>
        public static string UpdateMessage {
            get {
                return ResourceManager.GetString("UpdateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upload 的本地化字符串。
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upload Image 的本地化字符串。
        /// </summary>
        public static string UploadImage {
            get {
                return ResourceManager.GetString("UploadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upload Product 的本地化字符串。
        /// </summary>
        public static string UploadProduct {
            get {
                return ResourceManager.GetString("UploadProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View 的本地化字符串。
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Waitting 的本地化字符串。
        /// </summary>
        public static string Waitting {
            get {
                return ResourceManager.GetString("Waitting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Withdraw 的本地化字符串。
        /// </summary>
        public static string Withdraw {
            get {
                return ResourceManager.GetString("Withdraw", resourceCulture);
            }
        }
    }
}
