//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDMall.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Menu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Menu() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BDMall.Resources.Menu", typeof(Menu).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Add Category 的本地化字符串。
        /// </summary>
        public static string AddCategory {
            get {
                return ResourceManager.GetString("AddCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Content 的本地化字符串。
        /// </summary>
        public static string AddContent {
            get {
                return ResourceManager.GetString("AddContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bulk Update Price 的本地化字符串。
        /// </summary>
        public static string BulkUpdatePrice {
            get {
                return ResourceManager.GetString("BulkUpdatePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Carriage Setting 的本地化字符串。
        /// </summary>
        public static string CarriageSetting {
            get {
                return ResourceManager.GetString("CarriageSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Catalog 的本地化字符串。
        /// </summary>
        public static string Catalog {
            get {
                return ResourceManager.GetString("Catalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CMS 的本地化字符串。
        /// </summary>
        public static string CMS {
            get {
                return ResourceManager.GetString("CMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CMS Category 的本地化字符串。
        /// </summary>
        public static string CMSCategory {
            get {
                return ResourceManager.GetString("CMSCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Code Master 的本地化字符串。
        /// </summary>
        public static string CodeMaster {
            get {
                return ResourceManager.GetString("CodeMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Product Comment Management 的本地化字符串。
        /// </summary>
        public static string CommentMng {
            get {
                return ResourceManager.GetString("CommentMng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Combination Product List 的本地化字符串。
        /// </summary>
        public static string ComProductList {
            get {
                return ResourceManager.GetString("ComProductList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Country Setting 的本地化字符串。
        /// </summary>
        public static string CountrySetting {
            get {
                return ResourceManager.GetString("CountrySetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Currency Setting 的本地化字符串。
        /// </summary>
        public static string CurrencySetting {
            get {
                return ResourceManager.GetString("CurrencySetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom Price Range Setting 的本地化字符串。
        /// </summary>
        public static string CustomPriceRangeSetting {
            get {
                return ResourceManager.GetString("CustomPriceRangeSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data Export 的本地化字符串。
        /// </summary>
        public static string DataExport {
            get {
                return ResourceManager.GetString("DataExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DeliveryArranged Order 的本地化字符串。
        /// </summary>
        public static string DeliveryArramged {
            get {
                return ResourceManager.GetString("DeliveryArramged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delivery Management 的本地化字符串。
        /// </summary>
        public static string DeliveryMng {
            get {
                return ResourceManager.GetString("DeliveryMng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System Info.  的本地化字符串。
        /// </summary>
        public static string Desktop {
            get {
                return ResourceManager.GetString("Desktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Emailer 的本地化字符串。
        /// </summary>
        public static string Emailer {
            get {
                return ResourceManager.GetString("Emailer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Email Template Item 的本地化字符串。
        /// </summary>
        public static string EmailTempItem {
            get {
                return ResourceManager.GetString("EmailTempItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Email Templates 的本地化字符串。
        /// </summary>
        public static string EmailTemplates {
            get {
                return ResourceManager.GetString("EmailTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Email Type Items 的本地化字符串。
        /// </summary>
        public static string EmailTypeItems {
            get {
                return ResourceManager.GetString("EmailTypeItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Express Company 的本地化字符串。
        /// </summary>
        public static string ExpCompanySetting {
            get {
                return ResourceManager.GetString("ExpCompanySetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File Management 的本地化字符串。
        /// </summary>
        public static string FileManagement {
            get {
                return ResourceManager.GetString("FileManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stock Movement 的本地化字符串。
        /// </summary>
        public static string InventoryFlowRpt {
            get {
                return ResourceManager.GetString("InventoryFlowRpt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inventory List Search 的本地化字符串。
        /// </summary>
        public static string InventoryList {
            get {
                return ResourceManager.GetString("InventoryList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inventory Management 的本地化字符串。
        /// </summary>
        public static string InventoryMng {
            get {
                return ResourceManager.GetString("InventoryMng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Purchase And Location 的本地化字符串。
        /// </summary>
        public static string InventoryTransaction {
            get {
                return ResourceManager.GetString("InventoryTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last Month Reg. Member 的本地化字符串。
        /// </summary>
        public static string LastMonthRegMember {
            get {
                return ResourceManager.GetString("LastMonthRegMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Adjust Group Member 的本地化字符串。
        /// </summary>
        public static string ManageMemberGroup {
            get {
                return ResourceManager.GetString("ManageMemberGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Marketing 的本地化字符串。
        /// </summary>
        public static string Marketing {
            get {
                return ResourceManager.GetString("Marketing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mass Send Whatapps 的本地化字符串。
        /// </summary>
        public static string MassWhatapps {
            get {
                return ResourceManager.GetString("MassWhatapps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Member Group 的本地化字符串。
        /// </summary>
        public static string MemberGroup {
            get {
                return ResourceManager.GetString("MemberGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Member List 的本地化字符串。
        /// </summary>
        public static string MemberList {
            get {
                return ResourceManager.GetString("MemberList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Member Management 的本地化字符串。
        /// </summary>
        public static string MemberMng {
            get {
                return ResourceManager.GetString("MemberMng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Menu Management 的本地化字符串。
        /// </summary>
        public static string MenuMng {
            get {
                return ResourceManager.GetString("MenuMng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Merchant Account Setting 的本地化字符串。
        /// </summary>
        public static string MerchantAccountSetting {
            get {
                return ResourceManager.GetString("MerchantAccountSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Merchant List 的本地化字符串。
        /// </summary>
        public static string MerchantList {
            get {
                return ResourceManager.GetString("MerchantList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Merchant Management 的本地化字符串。
        /// </summary>
        public static string MerchantMng {
            get {
                return ResourceManager.GetString("MerchantMng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Order Managerment 的本地化字符串。
        /// </summary>
        public static string OrderMng {
            get {
                return ResourceManager.GetString("OrderMng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PaymentConfirmed Order 的本地化字符串。
        /// </summary>
        public static string PaymentConfirmed {
            get {
                return ResourceManager.GetString("PaymentConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Payment Methods 的本地化字符串。
        /// </summary>
        public static string PaymentManagement {
            get {
                return ResourceManager.GetString("PaymentManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Promotion Category 的本地化字符串。
        /// </summary>
        public static string PrmtCategory {
            get {
                return ResourceManager.GetString("PrmtCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Catalog Manager 的本地化字符串。
        /// </summary>
        public static string ProdCatalog {
            get {
                return ResourceManager.GetString("ProdCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Product Approve 的本地化字符串。
        /// </summary>
        public static string ProductApprove {
            get {
                return ResourceManager.GetString("ProductApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Product Attribute 的本地化字符串。
        /// </summary>
        public static string ProductAttribute {
            get {
                return ResourceManager.GetString("ProductAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Product Export 的本地化字符串。
        /// </summary>
        public static string ProductExport {
            get {
                return ResourceManager.GetString("ProductExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Product List 的本地化字符串。
        /// </summary>
        public static string ProductList {
            get {
                return ResourceManager.GetString("ProductList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Product Management 的本地化字符串。
        /// </summary>
        public static string ProductMng {
            get {
                return ResourceManager.GetString("ProductMng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Promotion 的本地化字符串。
        /// </summary>
        public static string Promotion {
            get {
                return ResourceManager.GetString("Promotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Order 的本地化字符串。
        /// </summary>
        public static string RecevedOrder {
            get {
                return ResourceManager.GetString("RecevedOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RegNPay 的本地化字符串。
        /// </summary>
        public static string RegNPay {
            get {
                return ResourceManager.GetString("RegNPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RegNPay Management 的本地化字符串。
        /// </summary>
        public static string RegNPayMng {
            get {
                return ResourceManager.GetString("RegNPayMng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Report 的本地化字符串。
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Return Order Management 的本地化字符串。
        /// </summary>
        public static string ReturnOrderMng {
            get {
                return ResourceManager.GetString("ReturnOrderMng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Role 的本地化字符串。
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sales Return 的本地化字符串。
        /// </summary>
        public static string SalesReturn {
            get {
                return ResourceManager.GetString("SalesReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shopping Discount Setup 的本地化字符串。
        /// </summary>
        public static string ShoppingDiscountSetup {
            get {
                return ResourceManager.GetString("ShoppingDiscountSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Member Spending Rank 的本地化字符串。
        /// </summary>
        public static string SpendingRank {
            get {
                return ResourceManager.GetString("SpendingRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Store Setting 的本地化字符串。
        /// </summary>
        public static string StoreSetting {
            get {
                return ResourceManager.GetString("StoreSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Supplier Setting 的本地化字符串。
        /// </summary>
        public static string SupplierSetting {
            get {
                return ResourceManager.GetString("SupplierSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System Setting 的本地化字符串。
        /// </summary>
        public static string SystemSetting {
            get {
                return ResourceManager.GetString("SystemSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This Month Reg. Member 的本地化字符串。
        /// </summary>
        public static string ThisMonthRegMember {
            get {
                return ResourceManager.GetString("ThisMonthRegMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User 的本地化字符串。
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User Management 的本地化字符串。
        /// </summary>
        public static string UserMng {
            get {
                return ResourceManager.GetString("UserMng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Location Setting 的本地化字符串。
        /// </summary>
        public static string WarehouseSetting {
            get {
                return ResourceManager.GetString("WarehouseSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warehouse SetUp 的本地化字符串。
        /// </summary>
        public static string WareHouseSetUp {
            get {
                return ResourceManager.GetString("WareHouseSetUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Zone Setting 的本地化字符串。
        /// </summary>
        public static string ZoneSetting {
            get {
                return ResourceManager.GetString("ZoneSetting", resourceCulture);
            }
        }
    }
}
