//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDMall.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Value {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Value() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BDMall.Resources.Value", typeof(Value).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Actived 的本地化字符串。
        /// </summary>
        public static string Actived {
            get {
                return ResourceManager.GetString("Actived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 approve 的本地化字符串。
        /// </summary>
        public static string approve {
            get {
                return ResourceManager.GetString("approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Approved 的本地化字符串。
        /// </summary>
        public static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Automatic 的本地化字符串。
        /// </summary>
        public static string Automatic {
            get {
                return ResourceManager.GetString("Automatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Pulled Off Shelves 的本地化字符串。
        /// </summary>
        public static string AutoOffSale {
            get {
                return ResourceManager.GetString("AutoOffSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Basic 的本地化字符串。
        /// </summary>
        public static string Basic {
            get {
                return ResourceManager.GetString("Basic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel Order 的本地化字符串。
        /// </summary>
        public static string CanceledOrder {
            get {
                return ResourceManager.GetString("CanceledOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cash Coupon 的本地化字符串。
        /// </summary>
        public static string CashCoupon {
            get {
                return ResourceManager.GetString("CashCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Decrease 的本地化字符串。
        /// </summary>
        public static string Decrease {
            get {
                return ResourceManager.GetString("Decrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delivery Arranged 的本地化字符串。
        /// </summary>
        public static string DeliveryArranged {
            get {
                return ResourceManager.GetString("DeliveryArranged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delivery Fee 的本地化字符串。
        /// </summary>
        public static string DeliveryFee {
            get {
                return ResourceManager.GetString("DeliveryFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Discount Coupon 的本地化字符串。
        /// </summary>
        public static string DiscountCoupon {
            get {
                return ResourceManager.GetString("DiscountCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Editing 的本地化字符串。
        /// </summary>
        public static string Editing {
            get {
                return ResourceManager.GetString("Editing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed 的本地化字符串。
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Finish 的本地化字符串。
        /// </summary>
        public static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 For Comment 的本地化字符串。
        /// </summary>
        public static string ForComment {
            get {
                return ResourceManager.GetString("ForComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 For Login 的本地化字符串。
        /// </summary>
        public static string ForLogin {
            get {
                return ResourceManager.GetString("ForLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 For ManuallyAdd 的本地化字符串。
        /// </summary>
        public static string ForManuallyAdd {
            get {
                return ResourceManager.GetString("ForManuallyAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 For Pickup 的本地化字符串。
        /// </summary>
        public static string ForPickup {
            get {
                return ResourceManager.GetString("ForPickup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 For Recommend 的本地化字符串。
        /// </summary>
        public static string ForRecommend {
            get {
                return ResourceManager.GetString("ForRecommend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 For Registered 的本地化字符串。
        /// </summary>
        public static string ForRegistered {
            get {
                return ResourceManager.GetString("ForRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 For Shopping 的本地化字符串。
        /// </summary>
        public static string ForShopping {
            get {
                return ResourceManager.GetString("ForShopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FreeShip Product 的本地化字符串。
        /// </summary>
        public static string FreeShipProduct {
            get {
                return ResourceManager.GetString("FreeShipProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GS1 的本地化字符串。
        /// </summary>
        public static string GS1 {
            get {
                return ResourceManager.GetString("GS1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 High Rating Product 的本地化字符串。
        /// </summary>
        public static string HightRatingProduct {
            get {
                return ResourceManager.GetString("HightRatingProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HotSale Product 的本地化字符串。
        /// </summary>
        public static string HotSaleProduct {
            get {
                return ResourceManager.GetString("HotSaleProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Back 的本地化字符串。
        /// </summary>
        public static string ImageBackSide {
            get {
                return ResourceManager.GetString("ImageBackSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Front 的本地化字符串。
        /// </summary>
        public static string ImageFrontSide {
            get {
                return ResourceManager.GetString("ImageFrontSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 In 的本地化字符串。
        /// </summary>
        public static string In {
            get {
                return ResourceManager.GetString("In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Increase 的本地化字符串。
        /// </summary>
        public static string Increase {
            get {
                return ResourceManager.GetString("Increase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 English 的本地化字符串。
        /// </summary>
        public static string LangEnglish {
            get {
                return ResourceManager.GetString("LangEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Japaness 的本地化字符串。
        /// </summary>
        public static string LangJapaness {
            get {
                return ResourceManager.GetString("LangJapaness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Simplified Chinese 的本地化字符串。
        /// </summary>
        public static string LangSimplifiedChinese {
            get {
                return ResourceManager.GetString("LangSimplifiedChinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Traditional Chinese 的本地化字符串。
        /// </summary>
        public static string LangTraditionalChinese {
            get {
                return ResourceManager.GetString("LangTraditionalChinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Timeout 的本地化字符串。
        /// </summary>
        public static string LoginTimeout {
            get {
                return ResourceManager.GetString("LoginTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mall 的本地化字符串。
        /// </summary>
        public static string Mall {
            get {
                return ResourceManager.GetString("Mall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Manual 的本地化字符串。
        /// </summary>
        public static string Manual {
            get {
                return ResourceManager.GetString("Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Manual Pulled Off Shelves 的本地化字符串。
        /// </summary>
        public static string ManualOffSale {
            get {
                return ResourceManager.GetString("ManualOffSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Product 的本地化字符串。
        /// </summary>
        public static string NewProduct {
            get {
                return ResourceManager.GetString("NewProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not Actived 的本地化字符串。
        /// </summary>
        public static string NotActived {
            get {
                return ResourceManager.GetString("NotActived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not Approved 的本地化字符串。
        /// </summary>
        public static string NotApproved {
            get {
                return ResourceManager.GetString("NotApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NotSent 的本地化字符串。
        /// </summary>
        public static string NotSent {
            get {
                return ResourceManager.GetString("NotSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NotStarted 的本地化字符串。
        /// </summary>
        public static string NotStarted {
            get {
                return ResourceManager.GetString("NotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pulled off the shelf 的本地化字符串。
        /// </summary>
        public static string OffSale {
            get {
                return ResourceManager.GetString("OffSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On Sale 的本地化字符串。
        /// </summary>
        public static string OnSale {
            get {
                return ResourceManager.GetString("OnSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string OrderByName {
            get {
                return ResourceManager.GetString("OrderByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Price 的本地化字符串。
        /// </summary>
        public static string OrderByPrice {
            get {
                return ResourceManager.GetString("OrderByPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Product Code 的本地化字符串。
        /// </summary>
        public static string OrderByProductCode {
            get {
                return ResourceManager.GetString("OrderByProductCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ascending 的本地化字符串。
        /// </summary>
        public static string OrderByTypeASC {
            get {
                return ResourceManager.GetString("OrderByTypeASC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Descending 的本地化字符串。
        /// </summary>
        public static string OrderByTypeDSC {
            get {
                return ResourceManager.GetString("OrderByTypeDSC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Order Completed AfterGrace Period 的本地化字符串。
        /// </summary>
        public static string OrderCompleteAfterGP {
            get {
                return ResourceManager.GetString("OrderCompleteAfterGP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Order Completed Within Grace Period 的本地化字符串。
        /// </summary>
        public static string OrderCompleteWithinGP {
            get {
                return ResourceManager.GetString("OrderCompleteWithinGP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Out 的本地化字符串。
        /// </summary>
        public static string Out {
            get {
                return ResourceManager.GetString("Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pass 的本地化字符串。
        /// </summary>
        public static string Pass {
            get {
                return ResourceManager.GetString("Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 For internal use only 的本地化字符串。
        /// </summary>
        public static string PermissionvForinternaluseonly {
            get {
                return ResourceManager.GetString("PermissionvForinternaluseonly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Viewable by public 的本地化字符串。
        /// </summary>
        public static string PermissionvVewablebypublic {
            get {
                return ResourceManager.GetString("PermissionvVewablebypublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Viewable after login 的本地化字符串。
        /// </summary>
        public static string PermissionvViewableafterlogin {
            get {
                return ResourceManager.GetString("PermissionvViewableafterlogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Price 的本地化字符串。
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Processing 的本地化字符串。
        /// </summary>
        public static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All Words 的本地化字符串。
        /// </summary>
        public static string ProductSearchTypeAllWords {
            get {
                return ResourceManager.GetString("ProductSearchTypeAllWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Any Word 的本地化字符串。
        /// </summary>
        public static string ProductSearchTypeAnyWord {
            get {
                return ResourceManager.GetString("ProductSearchTypeAnyWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refund 的本地化字符串。
        /// </summary>
        public static string Refund {
            get {
                return ResourceManager.GetString("Refund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refund Order(Cash and Mall Fun) 的本地化字符串。
        /// </summary>
        public static string RefundWithCashAndMallFun {
            get {
                return ResourceManager.GetString("RefundWithCashAndMallFun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reject 的本地化字符串。
        /// </summary>
        public static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sending 的本地化字符串。
        /// </summary>
        public static string Sendding {
            get {
                return ResourceManager.GetString("Sendding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sent 的本地化字符串。
        /// </summary>
        public static string Sent {
            get {
                return ResourceManager.GetString("Sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ON SALE 的本地化字符串。
        /// </summary>
        public static string SpecialItem_OnSale {
            get {
                return ResourceManager.GetString("SpecialItem_OnSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sale Off 的本地化字符串。
        /// </summary>
        public static string SpecialItem_SaleOff {
            get {
                return ResourceManager.GetString("SpecialItem_SaleOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Success 的本地化字符串。
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 To be on the shelf 的本地化字符串。
        /// </summary>
        public static string ToBeOnShelf {
            get {
                return ResourceManager.GetString("ToBeOnShelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Token Expire 的本地化字符串。
        /// </summary>
        public static string TokenExpire {
            get {
                return ResourceManager.GetString("TokenExpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown 的本地化字符串。
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logout 的本地化字符串。
        /// </summary>
        public static string UserLogout {
            get {
                return ResourceManager.GetString("UserLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WaitingApprove 的本地化字符串。
        /// </summary>
        public static string WaitingApprove {
            get {
                return ResourceManager.GetString("WaitingApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Waiting for the shelves 的本地化字符串。
        /// </summary>
        public static string WaitingOnSale {
            get {
                return ResourceManager.GetString("WaitingOnSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Waiting to send 的本地化字符串。
        /// </summary>
        public static string WaitingToSend {
            get {
                return ResourceManager.GetString("WaitingToSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wish List 的本地化字符串。
        /// </summary>
        public static string WishList {
            get {
                return ResourceManager.GetString("WishList", resourceCulture);
            }
        }
    }
}
